// <auto-generated />
using System;
using LuzyceApi.Db.AppDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuzyceApi.Db.AppDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240520083820_Documents")]
    partial class Documents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DocNumber")
                        .HasColumnType("int");

                    b.Property<int>("DocumentsDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentsDefinitionId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 20, 10, 38, 20, 450, DateTimeKind.Local).AddTicks(8856),
                            DocNumber = 1,
                            DocumentsDefinitionId = 1,
                            Number = "0001/KW/2023",
                            OperatorId = 1,
                            StatusId = 1,
                            UpdatedAt = new DateTime(2024, 5, 20, 10, 38, 20, 450, DateTimeKind.Local).AddTicks(8910),
                            WarehouseId = 1,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentItemRelationships", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NetQuantityParent")
                        .HasColumnType("int");

                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ParentPositionId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLossParent")
                        .HasColumnType("int");

                    b.Property<int>("SubordinateDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("SubordinatePositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("ParentPositionId");

                    b.HasIndex("SubordinateDocumentId");

                    b.HasIndex("SubordinatePositionId");

                    b.ToTable("DocumentItemRelationships");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentPositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrossQuantity")
                        .HasColumnType("int");

                    b.Property<int>("LampshadeId")
                        .HasColumnType("int");

                    b.Property<int>("NetQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLoss")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToImprove")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LampshadeId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("StatusId");

                    b.ToTable("DocumentPositions");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentRelations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("SubordinateDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("SubordinateDocumentId");

                    b.ToTable("DocumentRelations");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentsDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DocumentsDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KW",
                            Name = "Kwit"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Lampshade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lampshades");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("NetDeltaQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLossDelta")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToImproveDelta")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Otwarty",
                            Priority = 1
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Admin = true,
                            CreatedAt = new DateTime(2024, 5, 20, 10, 38, 20, 342, DateTimeKind.Local).AddTicks(7176),
                            Email = "admin@gmail.com",
                            Hash = "admin",
                            LastName = "Admin",
                            Login = "admin",
                            Name = "Admin",
                            Password = "$2a$11$Tn5Fjr2WIMVvxYpZNHLHqug5V4M2xguke6t2HKx15Mr8MmHa0vFWi"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MG",
                            Name = "Magazyn"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Document", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.DocumentsDefinition", "DocumentsDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentsDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentsDefinition");

                    b.Navigation("Operator");

                    b.Navigation("Status");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentItemRelationships", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Document", "ParentDocument")
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.DocumentPositions", "ParentPosition")
                        .WithMany()
                        .HasForeignKey("ParentPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Document", "SubordinateDocument")
                        .WithMany()
                        .HasForeignKey("SubordinateDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.DocumentPositions", "SubordinatePosition")
                        .WithMany()
                        .HasForeignKey("SubordinatePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDocument");

                    b.Navigation("ParentPosition");

                    b.Navigation("SubordinateDocument");

                    b.Navigation("SubordinatePosition");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentPositions", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Lampshade", "Lampshade")
                        .WithMany()
                        .HasForeignKey("LampshadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Lampshade");

                    b.Navigation("Operator");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.DocumentRelations", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Document", "ParentDocument")
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Document", "SubordinateDocument")
                        .WithMany()
                        .HasForeignKey("SubordinateDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDocument");

                    b.Navigation("SubordinateDocument");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Data.Models.Operation", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Data.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Operator");
                });
#pragma warning restore 612, 618
        }
    }
}
