// <auto-generated />
using System;
using LuzyceApi.Db.AppDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuzyceApi.Db.AppDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241013160807_changeWeightToDecimal")]
    partial class changeWeightToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test",
                            Symbol = "TST"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.CustomerLampshade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerSymbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LampshadeDekor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LampshadeId")
                        .HasColumnType("int");

                    b.Property<int>("LampshadeNormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LampshadeId");

                    b.HasIndex("LampshadeNormId");

                    b.ToTable("CustomerLampshades");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DocNumber")
                        .HasColumnType("int");

                    b.Property<int>("DocumentsDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("LockedById")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("po_OrderId");

                    b.Property<int?>("ProductionPlanPositionsId")
                        .HasColumnType("int")
                        .HasColumnName("kw_ProductionPlanPositionsId");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentsDefinitionId");

                    b.HasIndex("LockedById");

                    b.HasIndex("OperatorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductionPlanPositionsId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(6545),
                            DocNumber = 1,
                            DocumentsDefinitionId = 1,
                            Number = "M/0001/KW/2024",
                            OperatorId = 1,
                            ProductionPlanPositionsId = 1,
                            StatusId = 1,
                            UpdatedAt = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(6565),
                            WarehouseId = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(6571),
                            DocNumber = 1,
                            DocumentsDefinitionId = 2,
                            Number = "P/0001/ZP/2024",
                            OperatorId = 1,
                            StatusId = 1,
                            UpdatedAt = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(6575),
                            WarehouseId = 2,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentItemRelationships", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NetQuantityParent")
                        .HasColumnType("int");

                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ParentPositionId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLossParent")
                        .HasColumnType("int");

                    b.Property<int>("SubordinateDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("SubordinatePositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("ParentPositionId");

                    b.HasIndex("SubordinateDocumentId");

                    b.HasIndex("SubordinatePositionId");

                    b.ToTable("DocumentItemRelationships");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentPositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LampshadeDekor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LampshadeId")
                        .HasColumnType("int");

                    b.Property<int?>("LampshadeNormId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderPositionForProductionId")
                        .HasColumnType("int");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("po_Priority");

                    b.Property<int>("QuantityGross")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLoss")
                        .HasColumnType("int");

                    b.Property<int>("QuantityNetto")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToImprove")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SubiektProductId")
                        .HasColumnType("int")
                        .HasColumnName("po_SubiektProductId");

                    b.Property<decimal?>("po_NumberOfChanges")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("po_QuantityMade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LampshadeId");

                    b.HasIndex("LampshadeNormId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("OrderPositionForProductionId");

                    b.ToTable("DocumentPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentId = 1,
                            LampshadeDekor = "",
                            LampshadeId = 1,
                            OperatorId = 1,
                            QuantityGross = 0,
                            QuantityLoss = 0,
                            QuantityNetto = 0,
                            QuantityToImprove = 0,
                            Remarks = "",
                            StartTime = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(6994)
                        },
                        new
                        {
                            Id = 2,
                            DocumentId = 2,
                            LampshadeDekor = "F",
                            LampshadeId = 1,
                            LampshadeNormId = 1,
                            OperatorId = 1,
                            OrderPositionForProductionId = 1,
                            QuantityGross = 0,
                            QuantityLoss = 0,
                            QuantityNetto = 0,
                            QuantityToImprove = 0,
                            Remarks = "Test",
                            StartTime = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(7001),
                            SubiektProductId = 2628,
                            po_NumberOfChanges = 1m,
                            po_QuantityMade = 0
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentRelations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("SubordinateDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("SubordinateDocumentId");

                    b.ToTable("DocumentRelations");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentsDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DocumentsDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_DocumentsDefinitions_Code_MinLength", "LENGTH(`Code`) >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KW",
                            Name = "Kwit"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ZP",
                            Name = "Zlecenie Produkcji"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Lampshade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lampshades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KL4124"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.LampshadeNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LampshadeId")
                        .HasColumnType("int");

                    b.Property<string>("MethodOfPackaging")
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantityPerChange")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityPerPack")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightBrutto")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("WeightNetto")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("LampshadeId");

                    b.HasIndex("VariantId");

                    b.ToTable("LampshadeNorms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LampshadeId = 1,
                            MethodOfPackaging = "300x300x110",
                            QuantityPerChange = 50,
                            QuantityPerPack = 16,
                            VariantId = 1,
                            WeightBrutto = 3m,
                            WeightNetto = 0.45m
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.LampshadeVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LampshadeVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Opal",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 2,
                            Name = "Opal Mat",
                            ShortName = "M"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Opal Alabaster",
                            ShortName = "AL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Opal Falbanka",
                            ShortName = "FA"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jasny",
                            ShortName = "J"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jasny Kier",
                            ShortName = "J-KR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jasny Pladry",
                            ShortName = "J-PL"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jasny Antiko",
                            ShortName = "J-AC"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jasny Alabaster",
                            ShortName = "J-AL"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jasny Mat",
                            ShortName = "J-M"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jasny Mrożony",
                            ShortName = "J-MR"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorCodeId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLossDelta")
                        .HasColumnType("int");

                    b.Property<int>("QuantityNetDelta")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToImproveDelta")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ErrorCodeId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.OrderForProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("OrdersForProduction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(6787),
                            Number = "1",
                            OriginalNumber = "1"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.OrderPositionForProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderPositionLp")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductSymbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantityInStock")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderPositionsForProduction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test",
                            OrderId = 1,
                            OrderNumber = "1",
                            OrderPositionLp = 1,
                            ProductDescription = "Test",
                            ProductId = 1,
                            ProductName = "KL4124",
                            ProductSymbol = "KL4124",
                            Quantity = 1m,
                            QuantityInStock = 1m,
                            SerialNumber = "1",
                            Symbol = "TEST",
                            Unit = "szt"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.ProductionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("HeadsOfMetallurgicalTeamsId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeadsOfMetallurgicalTeamsId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProductionPlans", t =>
                        {
                            t.HasCheckConstraint("CK_ProductionPlans_Team_Range", "`Team` BETWEEN 1 AND 3");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 10, 13),
                            HeadsOfMetallurgicalTeamsId = 1,
                            ShiftId = 1,
                            StatusId = 1,
                            Team = 1
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.ProductionPlanPositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfHours")
                        .HasColumnType("int");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPositionId");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("ProductionPlanPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentPositionId = 2,
                            NumberOfHours = 8,
                            ProductionPlanId = 1,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hutmustrz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hutnik"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftSupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSupervisorId");

                    b.ToTable("Shifts", t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_ShiftNumber_Range", "`ShiftNumber` BETWEEN 1 AND 3");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 10, 13),
                            ShiftNumber = 1,
                            ShiftSupervisorId = 1
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Otwarty",
                            Priority = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Anulowany",
                            Priority = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zamknięty",
                            Priority = 30
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anulowany",
                            Priority = 40
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 18, 8, 6, 949, DateTimeKind.Local).AddTicks(6637),
                            Email = "admin@gmail.com",
                            Hash = "admin",
                            LastName = "Admin",
                            Login = "admin",
                            Name = "Admin",
                            Password = "$2a$11$so/gl0HcMpp3sibl6Zf43uRi2wXehbnLIhwjZVHKRsxmBWodb1e7u",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(5907),
                            Hash = "",
                            LastName = "Hutmustrz",
                            Login = "",
                            Name = "Przykładowy",
                            Password = "",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 13, 18, 8, 7, 56, DateTimeKind.Local).AddTicks(5972),
                            Hash = "",
                            LastName = "Hutnik",
                            Login = "",
                            Name = "Przykładowy",
                            Password = "",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_Code_MinLength", "LENGTH(`Code`) >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "M",
                            Name = "Magazyn"
                        },
                        new
                        {
                            Id = 2,
                            Code = "P",
                            Name = "Produkcja"
                        });
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.CustomerLampshade", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Lampshade", "Lampshade")
                        .WithMany()
                        .HasForeignKey("LampshadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.LampshadeNorm", "LampshadeNorm")
                        .WithMany()
                        .HasForeignKey("LampshadeNormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Lampshade");

                    b.Navigation("LampshadeNorm");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Document", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.DocumentsDefinition", "DocumentsDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentsDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Client", "LockedBy")
                        .WithMany()
                        .HasForeignKey("LockedById");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.OrderForProduction", "Order")
                        .WithMany("Documents")
                        .HasForeignKey("OrderId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.ProductionPlanPositions", "ProductionPlanPositions")
                        .WithMany("Kwit")
                        .HasForeignKey("ProductionPlanPositionsId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentsDefinition");

                    b.Navigation("LockedBy");

                    b.Navigation("Operator");

                    b.Navigation("Order");

                    b.Navigation("ProductionPlanPositions");

                    b.Navigation("Status");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentItemRelationships", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Document", "ParentDocument")
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.DocumentPositions", "ParentPosition")
                        .WithMany()
                        .HasForeignKey("ParentPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Document", "SubordinateDocument")
                        .WithMany()
                        .HasForeignKey("SubordinateDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.DocumentPositions", "SubordinatePosition")
                        .WithMany()
                        .HasForeignKey("SubordinatePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDocument");

                    b.Navigation("ParentPosition");

                    b.Navigation("SubordinateDocument");

                    b.Navigation("SubordinatePosition");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentPositions", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Document", "Document")
                        .WithMany("DocumentPositions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Lampshade", "Lampshade")
                        .WithMany()
                        .HasForeignKey("LampshadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.LampshadeNorm", "LampshadeNorm")
                        .WithMany()
                        .HasForeignKey("LampshadeNormId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.OrderPositionForProduction", "OrderPositionForProduction")
                        .WithMany()
                        .HasForeignKey("OrderPositionForProductionId");

                    b.Navigation("Document");

                    b.Navigation("Lampshade");

                    b.Navigation("LampshadeNorm");

                    b.Navigation("Operator");

                    b.Navigation("OrderPositionForProduction");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentRelations", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Document", "ParentDocument")
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Document", "SubordinateDocument")
                        .WithMany()
                        .HasForeignKey("SubordinateDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDocument");

                    b.Navigation("SubordinateDocument");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.LampshadeNorm", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Lampshade", "Lampshade")
                        .WithMany()
                        .HasForeignKey("LampshadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.LampshadeVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lampshade");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Log", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Operation", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Error", "ErrorCode")
                        .WithMany()
                        .HasForeignKey("ErrorCodeId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ErrorCode");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.OrderForProduction", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.OrderPositionForProduction", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.OrderForProduction", "Order")
                        .WithMany("OrderPosition")
                        .HasForeignKey("OrderId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Lampshade", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.ProductionPlan", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.User", "HeadsOfMetallurgicalTeams")
                        .WithMany()
                        .HasForeignKey("HeadsOfMetallurgicalTeamsId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.HasOne("LuzyceApi.Db.AppDb.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadsOfMetallurgicalTeams");

                    b.Navigation("Shift");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.ProductionPlanPositions", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.DocumentPositions", "DocumentPosition")
                        .WithMany("ProductionPlanPositions")
                        .HasForeignKey("DocumentPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuzyceApi.Db.AppDb.Models.ProductionPlan", "ProductionPlan")
                        .WithMany("Positions")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentPosition");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Shift", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.User", "ShiftSupervisor")
                        .WithMany()
                        .HasForeignKey("ShiftSupervisorId");

                    b.Navigation("ShiftSupervisor");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.User", b =>
                {
                    b.HasOne("LuzyceApi.Db.AppDb.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.Document", b =>
                {
                    b.Navigation("DocumentPositions");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.DocumentPositions", b =>
                {
                    b.Navigation("ProductionPlanPositions");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.OrderForProduction", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("OrderPosition");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.ProductionPlan", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("LuzyceApi.Db.AppDb.Models.ProductionPlanPositions", b =>
                {
                    b.Navigation("Kwit");
                });
#pragma warning restore 612, 618
        }
    }
}
