name: Build and Run Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop & clean old containers
        run: |
          if [ $(docker container ls -q -f name=luzyceapi) ]; then
            docker container stop luzyceapi
            docker container rm luzyceapi
          fi
          if [ $(docker image ls -q luzyceapi:latest) ]; then
            docker image rm luzyceapi:latest
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./LuzyceApi/Dockerfile
          push: false
          load: true
          tags: luzyceapi:latest

      - name: Run Docker container
        run: |
          docker run \
            -d \
            -p 8080:8080 \
            -p 8081:8081 \
            -e ConnectionStrings__AppDbConnection='${{ vars.CONNECTION_STRING_APP_DB }}' \
            -e ConnectionStrings__SubiektConnection='${{ vars.CONNECTION_STRING_SUBIEKT }}' \
            -e Jwt__SigningKey='${{ vars.JWT_SIGNING_KEY }}' \
            --name luzyceapi
            luzyceapi:latest

      - name: Check container logs
        run: |
          sleep 10
          docker logs $(docker ps -q --last 1)
